name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  google_maps_flutter: ^2.0.10
  geolocator: ^10.0.1
  sliding_up_panel: ^2.0.0
  geodesy: ^0.10.1
  firebase_auth: ^4.11.1
  firebase_core: ^2.19.0
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.1.14
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/id.png
    - assets/images/estacionamiento1.jpeg
    - assets/images/estacionamiento2.jpg
    - assets/images/estacionamiento3.jpeg
    - assets/images/constanera.png
    - assets/images/FloridaCenter.webp
    - assets/images/alameda.jpeg
    - assets/images/egana.png
    - assets/images/arauco.webp
    - assets/images/dominicos.jpeg
    - assets/images/Openkeneddy.png
    - assets/images/plazasur.jpg
    - assets/images/quilin.png
    - assets/images/vespuc.webp
    - assets/images/vespucio.png
    - assets/images/altolascondes.webp
    - assets/images/pladehesa.jpg
    - assets/images/plareina.png
    - assets/images/independencia.png
    - assets/images/psanbernardo.png
    - assets/images/mptobalaba.webp
    - assets/images/oppuentealto.png
    - assets/images/eupuentealto.png
    - assets/images/araucoelbosque.png
    - assets/images/mpoeste.png
    - assets/images/maipu.png
    - assets/images/quilicura.webp